version: '3'

networks:
   traefik-net:
      name: traefik-net
      external: true

services:
   traefik:
      image: traefik:v2.4
      container_name: traefik
      ports:
         - "80:80"
         - "433:433"
         - "8080:8080"
      volumes:
         # So that Traefik can listen to the Docker events
         - /var/run/docker.sock:/var/run/docker.sock
         - ./traefik_config/traefik.yml:/traefik.yml
         - ./traefik_config/dynamic_config:/dynamic_config
         - ./traefik_config/acme.json:/acme.json
      networks:
         - traefik-net
   
