http:
   services:
      carsides:
         loadBalancer:
            servers:
               - url: "http://carsides:55488"

   routers:
      carsides:
         rule: "Host(`carsides.localhost`)"
         entrypoints:
            - "webs"
         service: "carsides"
